-- MySQL Script generated by MySQL Workbench
-- Mon Aug 19 22:05:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema genetic_algorithms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema genetic_algorithms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `genetic_algorithms` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE `genetic_algorithms`;

-- -----------------------------------------------------
-- Table `genetic_algorithms`.`runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genetic_algorithms`.`runs`
(
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `genetic_algorithms`.`censuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genetic_algorithms`.`censuses`
(
    `id`           INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `run_id`       INT UNSIGNED     NOT NULL,
    `date_created` DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`, `run_id`),
    INDEX `fk_censuses_runs1_idx` (`run_id` ASC) VISIBLE,
    CONSTRAINT `fk_censuses_runs1`
        FOREIGN KEY (`run_id`)
            REFERENCES `genetic_algorithms`.`runs` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genetic_algorithms`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genetic_algorithms`.`species`
(
    `id`     INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `run_id` INT UNSIGNED     NOT NULL,
    `name`   VARCHAR(45)      NOT NULL,
    PRIMARY KEY (`id`, `run_id`),
    INDEX `fk_species_runs1_idx` (`run_id` ASC) VISIBLE,
    CONSTRAINT `fk_species_runs1`
        FOREIGN KEY (`run_id`)
            REFERENCES `genetic_algorithms`.`runs` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 620
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genetic_algorithms`.`creatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genetic_algorithms`.`creatures`
(
    `id`                   INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `run_id`               INT UNSIGNED     NOT NULL,
    `species_id`           INT(10) UNSIGNED NOT NULL,
    `age`                  INT(10) UNSIGNED NOT NULL,
    `replication_chance`   DOUBLE           NOT NULL,
    `death_chance`         DOUBLE           NOT NULL,
    `speed`                DOUBLE           NOT NULL,
    `size`                 DOUBLE           NOT NULL,
    `colour_red`           DOUBLE           NOT NULL,
    `colour_green`         DOUBLE           NOT NULL,
    `colour_blue`          DOUBLE           NOT NULL,
    `metabolic_efficiency` DOUBLE           NOT NULL,
    `sensory_range`        DOUBLE           NOT NULL,
    `greediness`           DOUBLE           NOT NULL,
    `thriftiness`          DOUBLE           NOT NULL,
    `shininess`            DOUBLE           NOT NULL,
    PRIMARY KEY (`id`, `run_id`),
    INDEX `fk_creatures_runs1_idx` (`run_id` ASC) VISIBLE,
    INDEX `fk_creatures_species1_idx` (`species_id` ASC, `run_id` ASC) VISIBLE,
    CONSTRAINT `fk_creatures_runs1`
        FOREIGN KEY (`run_id`)
            REFERENCES `genetic_algorithms`.`runs` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_creatures_species1`
        FOREIGN KEY (`species_id`, `run_id`)
            REFERENCES `genetic_algorithms`.`species` (`id`, `run_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 2965
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `genetic_algorithms`.`census_participants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `genetic_algorithms`.`census_participants`
(
    `run_id`      INT UNSIGNED     NOT NULL,
    `census_id`   INT(10) UNSIGNED NOT NULL,
    `creature_id` INT(10) UNSIGNED NOT NULL,
    PRIMARY KEY (`run_id`, `census_id`, `creature_id`),
    INDEX `fk_census_participants_runs1_idx` (`run_id` ASC) VISIBLE,
    INDEX `fk_census_participants_creatures1_idx` (`creature_id` ASC, `run_id` ASC) VISIBLE,
    CONSTRAINT `fk_census_participants_runs1`
        FOREIGN KEY (`run_id`)
            REFERENCES `genetic_algorithms`.`runs` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_census_participants_censuses1`
        FOREIGN KEY (`run_id`, `census_id`)
            REFERENCES `genetic_algorithms`.`censuses` (`run_id`, `id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_census_participants_creatures1`
        FOREIGN KEY (`creature_id`, `run_id`)
            REFERENCES `genetic_algorithms`.`creatures` (`id`, `run_id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
