version: '3.3'
services:
  db:
    image: mysql:5.7.27
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db: